/*
 * herald_agent.c — NML Collective Herald.
 *
 * Supervises the MQTT broker (Mosquitto), manages credentials and ACLs,
 * and exposes a minimal HTTP REST API for credential operations.
 *
 * The Herald is pure infrastructure — it does NOT join the mesh as a peer.
 * Every agent in the collective connects through the Herald.
 *
 * Usage:
 *   ./herald_agent [--name NAME] [--broker-port PORT] [--api-port PORT]
 *                  [--config-dir DIR] [--mosquitto PATH]
 *                  [--mosquitto-passwd PATH] [--no-auth]
 *
 * REST API:
 *   POST /credentials/issue   — issue a credential (agent + password + role)
 *   POST /credentials/revoke  — revoke a credential (agent)
 *   GET  /health              — broker and registry status
 */

#define _POSIX_C_SOURCE 200809L

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <time.h>
#include <errno.h>

#include "../../edge/compat.h"

#ifdef COMPAT_POSIX
#include <sys/types.h>
#include <sys/wait.h>
#endif

/* ── Constants ───────────────────────────────────────────────────────── */

#define MAX_CREDS          128
#define MAX_PATH_LEN       512
#define HTTP_BUF_SZ        8192
#define JSON_VAL_SZ        256
#define MAX_RESTARTS       20
#define RESTART_DELAY_SEC  3
#define BROKER_CHECK_SEC   2
#define LOG_INTERVAL_SEC   60

/* ── Types ───────────────────────────────────────────────────────────── */

typedef struct {
    char   name[JSON_VAL_SZ];
    char   role[JSON_VAL_SZ];
    time_t issued_at;
} CredEntry;

/* ── Globals ─────────────────────────────────────────────────────────── */

static volatile int g_running = 1;
static void on_signal(int sig) { (void)sig; g_running = 0; }

#ifdef COMPAT_WINDOWS
static HANDLE g_broker_handle     = NULL;
static DWORD  g_broker_pid        = 0;
#else
static pid_t  g_broker_pid        = -1;
#endif
static int    g_broker_running    = 0;
static int    g_broker_restarts   = 0;
static time_t g_broker_last_start = 0;

static CredEntry g_creds[MAX_CREDS];
static int       g_cred_count = 0;

static const char *g_agent_name = "herald";
static int         g_broker_port = 1883;
static int         g_api_port    = 7780;
static char        g_config_dir[MAX_PATH_LEN];
static char        g_conf_file[MAX_PATH_LEN + 32];
static char        g_passwd_file[MAX_PATH_LEN + 32];
static char        g_acl_file[MAX_PATH_LEN + 32];
static char        g_mosquitto_bin[MAX_PATH_LEN];
static char        g_mosquitto_passwd_bin[MAX_PATH_LEN];
static int         g_no_auth = 0;

/* ── Config generation ───────────────────────────────────────────────── */

static int write_mosquitto_conf(void)
{
    FILE *f = fopen(g_conf_file, "w");
    if (!f) {
        fprintf(stderr, "[%s] failed to open %s: %s\n",
                g_agent_name, g_conf_file, strerror(errno));
        return -1;
    }

    fprintf(f, "# NML Collective Herald — generated by herald_agent\n");
    fprintf(f, "# Do not edit; changes will be overwritten on restart.\n\n");

    fprintf(f, "listener %d\n", g_broker_port);
    fprintf(f, "protocol mqtt\n\n");

    if (g_no_auth) {
        fprintf(f, "allow_anonymous true\n");
    } else {
        fprintf(f, "allow_anonymous false\n");
        fprintf(f, "password_file %s\n", g_passwd_file);
        fprintf(f, "acl_file %s\n", g_acl_file);
    }

    fprintf(f, "\nretain_available true\n");
    fprintf(f, "persistence false\n\n");

    fprintf(f, "log_type error\n");
    fprintf(f, "log_type warning\n");
    fprintf(f, "log_type notice\n");
    fprintf(f, "log_dest stdout\n\n");

    fprintf(f, "sys_interval 10\n");

    fclose(f);

    printf("[%s] wrote %s (port=%d, auth=%s)\n",
           g_agent_name, g_conf_file, g_broker_port,
           g_no_auth ? "off" : "on");
    return 0;
}

static int write_acl_file(void)
{
    if (g_no_auth) {
        return 0;
    }

    FILE *f = fopen(g_acl_file, "w");
    if (!f) {
        fprintf(stderr, "[%s] failed to open %s: %s\n",
                g_agent_name, g_acl_file, strerror(errno));
        return -1;
    }

    fprintf(f, "# NML Collective ACL — managed by herald_agent\n\n");
    fprintf(f, "topic readwrite nml/#\n\n");

    for (int i = 0; i < g_cred_count; i++) {
        const char *r = g_creds[i].role;
        if (strcmp(r, "sentient") == 0 ||
            strcmp(r, "enforcer") == 0 ||
            strcmp(r, "herald")   == 0) {
            fprintf(f, "user %s\n", g_creds[i].name);
            fprintf(f, "topic readwrite nml/#\n");
            fprintf(f, "topic readwrite $SYS/#\n\n");
        }
    }

    fclose(f);
    return 0;
}

/* ── Broker process management ───────────────────────────────────────── */

#ifdef COMPAT_WINDOWS

/* ── Windows: CreateProcess / TerminateProcess ─────────────────────── */

static int run_command(const char *bin, char *const argv[])
{
    /* Build a flat command line from argv[] */
    char cmdline[2048];
    int pos = 0;
    for (int i = 0; argv[i]; i++) {
        if (i > 0) cmdline[pos++] = ' ';
        pos += snprintf(cmdline + pos, sizeof(cmdline) - (size_t)pos,
                        "%s", argv[i]);
    }

    STARTUPINFOA si;
    PROCESS_INFORMATION pi;
    memset(&si, 0, sizeof(si));
    si.cb = sizeof(si);
    memset(&pi, 0, sizeof(pi));

    if (!CreateProcessA(bin, cmdline, NULL, NULL, FALSE,
                        0, NULL, NULL, &si, &pi)) {
        fprintf(stderr, "[%s] CreateProcess %s failed (err=%lu)\n",
                g_agent_name, bin, GetLastError());
        return -1;
    }
    WaitForSingleObject(pi.hProcess, INFINITE);
    DWORD code = 0;
    GetExitCodeProcess(pi.hProcess, &code);
    CloseHandle(pi.hProcess);
    CloseHandle(pi.hThread);
    return (int)code;
}

static int broker_start(void)
{
    if (g_broker_running && g_broker_handle) {
        return 0;
    }

    time_t now = time(NULL);
    if (g_broker_last_start > 0 &&
        (now - g_broker_last_start) < RESTART_DELAY_SEC) {
        return 0;
    }

    if (g_broker_restarts >= MAX_RESTARTS) {
        fprintf(stderr, "[%s] broker exceeded max restarts\n", g_agent_name);
        g_running = 0;
        return -1;
    }

    char cmdline[2048];
    snprintf(cmdline, sizeof(cmdline), "\"%s\" -c \"%s\"",
             g_mosquitto_bin, g_conf_file);

    STARTUPINFOA si;
    PROCESS_INFORMATION pi;
    memset(&si, 0, sizeof(si));
    si.cb = sizeof(si);
    memset(&pi, 0, sizeof(pi));

    if (!CreateProcessA(NULL, cmdline, NULL, NULL, FALSE,
                        0, NULL, NULL, &si, &pi)) {
        fprintf(stderr, "[%s] CreateProcess failed (err=%lu)\n",
                g_agent_name, GetLastError());
        return -1;
    }

    g_broker_handle = pi.hProcess;
    g_broker_pid = pi.dwProcessId;
    CloseHandle(pi.hThread);
    g_broker_running = 1;
    g_broker_restarts++;
    g_broker_last_start = now;

    printf("[%s] broker started (pid=%lu, restart=%d)\n",
           g_agent_name, (unsigned long)g_broker_pid, g_broker_restarts);
    return 0;
}

static void broker_reload(void)
{
    /* Windows has no SIGHUP equivalent for Mosquitto — restart instead */
    if (g_broker_handle) {
        printf("[%s] reload requested — restarting broker on Windows\n",
               g_agent_name);
        /* broker_check will detect exit and trigger restart */
        TerminateProcess(g_broker_handle, 0);
    }
}

static void broker_stop(void)
{
    if (!g_broker_handle) {
        return;
    }

    printf("[%s] stopping broker (pid=%lu)\n",
           g_agent_name, (unsigned long)g_broker_pid);

    /* Give broker 5 seconds to exit gracefully */
    TerminateProcess(g_broker_handle, 0);
    WaitForSingleObject(g_broker_handle, 5000);

    CloseHandle(g_broker_handle);
    g_broker_handle = NULL;
    g_broker_pid = 0;
    g_broker_running = 0;
}

static int broker_check(void)
{
    if (!g_broker_handle) {
        return 1; /* not running */
    }

    DWORD result = WaitForSingleObject(g_broker_handle, 0);
    if (result == WAIT_TIMEOUT) {
        return 0; /* still running */
    }

    DWORD code = 0;
    GetExitCodeProcess(g_broker_handle, &code);
    printf("[%s] broker exited (status=%lu), will restart\n",
           g_agent_name, (unsigned long)code);
    CloseHandle(g_broker_handle);
    g_broker_handle = NULL;
    g_broker_pid = 0;
    g_broker_running = 0;
    return 1;
}

#else /* POSIX */

static int run_command(const char *bin, char *const argv[])
{
    pid_t pid = fork();
    if (pid < 0) {
        fprintf(stderr, "[%s] fork failed: %s\n", g_agent_name, strerror(errno));
        return -1;
    }
    if (pid == 0) {
        execv(bin, argv);
        fprintf(stderr, "[%s] execv %s failed: %s\n",
                g_agent_name, bin, strerror(errno));
        _exit(1);
    }
    int status = 0;
    waitpid(pid, &status, 0);
    if (WIFEXITED(status)) {
        return WEXITSTATUS(status);
    }
    return -1;
}

static int broker_start(void)
{
    if (g_broker_running && g_broker_pid > 0) {
        return 0;
    }

    time_t now = time(NULL);
    if (g_broker_last_start > 0 &&
        (now - g_broker_last_start) < RESTART_DELAY_SEC) {
        return 0;
    }

    if (g_broker_restarts >= MAX_RESTARTS) {
        fprintf(stderr, "[%s] broker exceeded max restarts\n", g_agent_name);
        g_running = 0;
        return -1;
    }

    pid_t pid = fork();
    if (pid < 0) {
        fprintf(stderr, "[%s] fork failed: %s\n", g_agent_name, strerror(errno));
        return -1;
    }
    if (pid == 0) {
        execl(g_mosquitto_bin, g_mosquitto_bin, "-c", g_conf_file, (char *)NULL);
        fprintf(stderr, "[herald] execl %s failed: %s\n",
                g_mosquitto_bin, strerror(errno));
        _exit(1);
    }

    g_broker_pid = pid;
    g_broker_running = 1;
    g_broker_restarts++;
    g_broker_last_start = now;

    printf("[%s] broker started (pid=%d, restart=%d)\n",
           g_agent_name, (int)g_broker_pid, g_broker_restarts);
    return 0;
}

static void broker_reload(void)
{
    if (g_broker_pid > 0) {
        kill(g_broker_pid, SIGHUP);
    }
}

static void broker_stop(void)
{
    if (g_broker_pid <= 0) {
        return;
    }

    printf("[%s] stopping broker (pid=%d)\n", g_agent_name, (int)g_broker_pid);
    kill(g_broker_pid, SIGTERM);

    for (int i = 0; i < 50; i++) {
        struct timeval tv;
        tv.tv_sec  = 0;
        tv.tv_usec = 100000; /* 100ms */
        select(0, NULL, NULL, NULL, &tv);

        int status = 0;
        pid_t r = waitpid(g_broker_pid, &status, WNOHANG);
        if (r == g_broker_pid) {
            g_broker_pid = -1;
            g_broker_running = 0;
            return;
        }
    }

    kill(g_broker_pid, SIGKILL);
    waitpid(g_broker_pid, NULL, 0);
    g_broker_pid = -1;
    g_broker_running = 0;
}

static int broker_check(void)
{
    if (g_broker_pid <= 0) {
        return 1;
    }

    int status = 0;
    pid_t r = waitpid(g_broker_pid, &status, WNOHANG);

    if (r == 0) {
        return 0; /* still running */
    }

    if (r == g_broker_pid) {
        int code = WIFEXITED(status) ? WEXITSTATUS(status) : -1;
        printf("[%s] broker exited (status=%d), will restart\n",
               g_agent_name, code);
        g_broker_pid = -1;
        g_broker_running = 0;
        return 1;
    }

    return 0;
}

#endif /* COMPAT_WINDOWS / POSIX */

/* ── Credential management ───────────────────────────────────────────── */

static int safe_name(const char *s)
{
    if (!s || s[0] == '\0') {
        return -1;
    }
    for (const char *p = s; *p; p++) {
        char c = *p;
        int ok = ((c >= 'a' && c <= 'z') ||
                  (c >= 'A' && c <= 'Z') ||
                  (c >= '0' && c <= '9') ||
                  c == '-' || c == '_');
        if (!ok) {
            return -1;
        }
    }
    return 0;
}

static int safe_password(const char *s)
{
    if (!s || s[0] == '\0') {
        return -1;
    }
    for (const char *p = s; *p; p++) {
        unsigned char c = (unsigned char)*p;
        if (c < 0x20 || c > 0x7e) {
            return -1;
        }
        if (*p == '\'' || *p == '\\') {
            return -1;
        }
    }
    return 0;
}

static int cred_find(const char *name)
{
    for (int i = 0; i < g_cred_count; i++) {
        if (strncmp(g_creds[i].name, name, 63) == 0) {
            return i;
        }
    }
    return -1;
}

static int cred_issue(const char *name, const char *password, const char *role)
{
    if (safe_name(name) < 0) {
        fprintf(stderr, "[%s] invalid credential name\n", g_agent_name);
        return -1;
    }
    if (!g_no_auth && safe_password(password) < 0) {
        fprintf(stderr, "[%s] invalid credential password\n", g_agent_name);
        return -1;
    }

    if (!g_no_auth) {
        char *argv[] = {
            g_mosquitto_passwd_bin,
            "-b",
            g_passwd_file,
            (char *)name,
            (char *)password,
            NULL
        };
        int rc = run_command(g_mosquitto_passwd_bin, argv);
        if (rc != 0) {
            fprintf(stderr, "[%s] mosquitto_passwd failed (rc=%d)\n",
                    g_agent_name, rc);
            return -1;
        }
    }

    int idx = cred_find(name);
    if (idx >= 0) {
        /* update in place */
    } else if (g_cred_count >= MAX_CREDS) {
        fprintf(stderr, "[%s] credential store full\n", g_agent_name);
        return -1;
    } else {
        idx = g_cred_count++;
    }

    snprintf(g_creds[idx].name, sizeof(g_creds[idx].name), "%s", name);

    const char *effective_role = (role && role[0] != '\0') ? role : "worker";
    snprintf(g_creds[idx].role, sizeof(g_creds[idx].role), "%s", effective_role);

    g_creds[idx].issued_at = time(NULL);

    write_acl_file();
    broker_reload();

    printf("[%s] issued credential: %s (role=%s)\n",
           g_agent_name, name, g_creds[idx].role);
    return 0;
}

static int cred_revoke(const char *name)
{
    if (safe_name(name) < 0) {
        fprintf(stderr, "[%s] invalid credential name\n", g_agent_name);
        return -1;
    }

    if (!g_no_auth) {
        char *argv[] = {
            g_mosquitto_passwd_bin,
            "-D",
            g_passwd_file,
            (char *)name,
            NULL
        };
        run_command(g_mosquitto_passwd_bin, argv);
    }

    int idx = cred_find(name);
    if (idx >= 0) {
        int remaining = g_cred_count - idx - 1;
        if (remaining > 0) {
            memmove(&g_creds[idx], &g_creds[idx + 1],
                    (size_t)remaining * sizeof(CredEntry));
        }
        g_cred_count--;
    }

    write_acl_file();
    broker_reload();

    printf("[%s] revoked credential: %s\n", g_agent_name, name);
    return 0;
}

/* ── Minimal HTTP server ─────────────────────────────────────────────── */

static int json_str(const char *json, const char *key,
                    char *out_buf, size_t out_sz)
{
    if (!json || !key || !out_buf || out_sz == 0) {
        return -1;
    }

    /* find "key" */
    char needle[JSON_VAL_SZ];
    snprintf(needle, sizeof(needle), "\"%s\"", key);

    const char *p = strstr(json, needle);
    if (!p) {
        return -1;
    }
    p += strlen(needle);

    /* skip whitespace and colon */
    while (*p == ' ' || *p == '\t' || *p == '\r' || *p == '\n') p++;
    if (*p != ':') {
        return -1;
    }
    p++;
    while (*p == ' ' || *p == '\t' || *p == '\r' || *p == '\n') p++;

    /* expect opening quote */
    if (*p != '"') {
        return -1;
    }
    p++;

    size_t written = 0;
    while (*p && *p != '"') {
        if (written < out_sz - 1) {
            out_buf[written++] = *p;
        }
        p++;
    }
    out_buf[written] = '\0';

    if (*p != '"') {
        return -1;
    }
    return 0;
}

static void http_respond(compat_socket_t fd, int status, const char *body)
{
    const char *status_str;
    switch (status) {
    case 200: status_str = "OK";                    break;
    case 400: status_str = "Bad Request";           break;
    case 404: status_str = "Not Found";             break;
    case 405: status_str = "Method Not Allowed";    break;
    default:  status_str = "Internal Server Error"; break;
    }

    size_t body_len = body ? strlen(body) : 0;

    char header[1024];
    snprintf(header, sizeof(header),
             "HTTP/1.0 %d %s\r\n"
             "Content-Type: application/json\r\n"
             "Content-Length: %zu\r\n"
             "Access-Control-Allow-Origin: *\r\n"
             "Access-Control-Allow-Headers: Content-Type, Authorization\r\n"
             "Connection: close\r\n"
             "\r\n",
             status, status_str, body_len);

    send(fd, header, strlen(header), 0);
    if (body && body_len > 0) {
        send(fd, body, body_len, 0);
    }
}

static void handle_health(compat_socket_t fd)
{
    char body[512];
    snprintf(body, sizeof(body),
             "{\"status\":\"%s\",\"broker_pid\":%d,"
             "\"broker_restarts\":%d,\"credentials\":%d,"
             "\"broker_port\":%d,\"api_port\":%d}",
             g_broker_running ? "healthy" : "broker_down",
             (int)g_broker_pid,
             g_broker_restarts,
             g_cred_count,
             g_broker_port,
             g_api_port);
    http_respond(fd, 200, body);
}

static void handle_issue(compat_socket_t fd, const char *body)
{
    char agent[JSON_VAL_SZ];
    char password[JSON_VAL_SZ];
    char role[JSON_VAL_SZ];

    if (json_str(body, "agent", agent, sizeof(agent)) < 0 ||
        json_str(body, "password", password, sizeof(password)) < 0) {
        http_respond(fd, 400, "{\"error\":\"agent and password required\"}");
        return;
    }

    if (json_str(body, "role", role, sizeof(role)) < 0) {
        snprintf(role, sizeof(role), "worker");
    }

    if (cred_issue(agent, password, role) < 0) {
        http_respond(fd, 400, "{\"error\":\"credential issue failed\"}");
        return;
    }

    char resp[1024];
    snprintf(resp, sizeof(resp),
             "{\"issued\":\"%s\",\"role\":\"%s\"}", agent, role);
    http_respond(fd, 200, resp);
}

static void handle_revoke(compat_socket_t fd, const char *body)
{
    char agent[JSON_VAL_SZ];

    if (json_str(body, "agent", agent, sizeof(agent)) < 0) {
        http_respond(fd, 400, "{\"error\":\"agent required\"}");
        return;
    }

    cred_revoke(agent);

    char resp[512];
    snprintf(resp, sizeof(resp), "{\"revoked\":\"%s\"}", agent);
    http_respond(fd, 200, resp);
}

static void http_serve_once(compat_socket_t server_fd)
{
    compat_socket_t client_fd = accept(server_fd, NULL, NULL);
    if (client_fd == COMPAT_INVALID_SOCKET) {
        return;
    }

    static char buf[HTTP_BUF_SZ];
    int total = 0;
    int found_headers = 0;

    /* read until \r\n\r\n found or buffer full */
    while (total < HTTP_BUF_SZ - 1) {
        int n = (int)recv(client_fd, buf + total, (size_t)(HTTP_BUF_SZ - 1 - total), 0);
        if (n <= 0) {
            break;
        }
        total += n;
        buf[total] = '\0';
        if (strstr(buf, "\r\n\r\n")) {
            found_headers = 1;
            break;
        }
    }

    if (!found_headers) {
        compat_close_socket(client_fd);
        return;
    }

    buf[total] = '\0';

    /* parse method and path from first line */
    char method[16] = {0};
    char path[256]  = {0};
    sscanf(buf, "%15s %255s", method, path);

    /* find body pointer (after \r\n\r\n) */
    char *body_ptr = strstr(buf, "\r\n\r\n");
    if (body_ptr) {
        body_ptr += 4;
    } else {
        body_ptr = buf + total;
    }

    /* check Content-Length and read more body data if needed */
    char *cl_hdr = strstr(buf, "Content-Length:");
    if (!cl_hdr) {
        cl_hdr = strstr(buf, "content-length:");
    }
    if (cl_hdr) {
        int content_length = 0;
        sscanf(cl_hdr + 15, " %d", &content_length);

        int body_have = (int)(buf + total - body_ptr);
        while (body_have < content_length && total < HTTP_BUF_SZ - 1) {
            int n = (int)recv(client_fd, buf + total,
                              (size_t)(HTTP_BUF_SZ - 1 - total), 0);
            if (n <= 0) {
                break;
            }
            total += n;
            body_have += n;
        }
        buf[total] = '\0';
        /* recompute body_ptr after potential realloc-less resize */
        body_ptr = strstr(buf, "\r\n\r\n");
        if (body_ptr) {
            body_ptr += 4;
        } else {
            body_ptr = buf + total;
        }
    }

    /* dispatch */
    if (strcmp(method, "GET") == 0 && strcmp(path, "/health") == 0) {
        handle_health(client_fd);
    } else if (strcmp(method, "POST") == 0 &&
               strcmp(path, "/credentials/issue") == 0) {
        handle_issue(client_fd, body_ptr);
    } else if (strcmp(method, "POST") == 0 &&
               strcmp(path, "/credentials/revoke") == 0) {
        handle_revoke(client_fd, body_ptr);
    } else if (strcmp(method, "OPTIONS") == 0) {
        http_respond(client_fd, 200, "{}");
    } else {
        http_respond(client_fd, 404, "{\"error\":\"not found\"}");
    }

    compat_close_socket(client_fd);
}

static compat_socket_t make_server_socket(int port)
{
    compat_socket_t fd = socket(AF_INET, SOCK_STREAM, 0);
    if (fd == COMPAT_INVALID_SOCKET) {
        fprintf(stderr, "[%s] socket: %s\n", g_agent_name, strerror(errno));
        return COMPAT_INVALID_SOCKET;
    }

    int opt = 1;
    setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, COMPAT_SOCKOPT_CAST(&opt), sizeof(opt));

    struct sockaddr_in addr;
    memset(&addr, 0, sizeof(addr));
    addr.sin_family      = AF_INET;
    addr.sin_addr.s_addr = INADDR_ANY;
    addr.sin_port        = htons((uint16_t)port);

    if (bind(fd, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
        fprintf(stderr, "[%s] bind port %d: %s\n",
                g_agent_name, port, strerror(errno));
        compat_close_socket(fd);
        return COMPAT_INVALID_SOCKET;
    }

    if (listen(fd, 8) < 0) {
        fprintf(stderr, "[%s] listen: %s\n", g_agent_name, strerror(errno));
        compat_close_socket(fd);
        return COMPAT_INVALID_SOCKET;
    }

    return fd;
}

/* ── main ────────────────────────────────────────────────────────────── */

int main(int argc, char *argv[])
{
    /* defaults */
    snprintf(g_config_dir,         sizeof(g_config_dir),         "/tmp/nml-herald");
    snprintf(g_mosquitto_bin,      sizeof(g_mosquitto_bin),      "mosquitto");
    snprintf(g_mosquitto_passwd_bin, sizeof(g_mosquitto_passwd_bin), "mosquitto_passwd");

    /* parse args */
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--name") == 0 && i + 1 < argc) {
            g_agent_name = argv[++i];
        } else if (strcmp(argv[i], "--broker-port") == 0 && i + 1 < argc) {
            g_broker_port = atoi(argv[++i]);
        } else if (strcmp(argv[i], "--api-port") == 0 && i + 1 < argc) {
            g_api_port = atoi(argv[++i]);
        } else if (strcmp(argv[i], "--config-dir") == 0 && i + 1 < argc) {
            snprintf(g_config_dir, sizeof(g_config_dir), "%s", argv[++i]);
        } else if (strcmp(argv[i], "--mosquitto") == 0 && i + 1 < argc) {
            snprintf(g_mosquitto_bin, sizeof(g_mosquitto_bin), "%s", argv[++i]);
        } else if (strcmp(argv[i], "--mosquitto-passwd") == 0 && i + 1 < argc) {
            snprintf(g_mosquitto_passwd_bin, sizeof(g_mosquitto_passwd_bin),
                     "%s", argv[++i]);
        } else if (strcmp(argv[i], "--no-auth") == 0) {
            g_no_auth = 1;
        } else {
            fprintf(stderr,
                    "Usage: %s [--name NAME] [--broker-port PORT] [--api-port PORT]\n"
                    "          [--config-dir DIR] [--mosquitto PATH]\n"
                    "          [--mosquitto-passwd PATH] [--no-auth]\n",
                    argv[0]);
            return 1;
        }
    }

    compat_winsock_init();

    /* build derived paths */
    snprintf(g_conf_file,   sizeof(g_conf_file),   "%s/mosquitto.conf", g_config_dir);
    snprintf(g_passwd_file, sizeof(g_passwd_file),  "%s/passwd",         g_config_dir);
    snprintf(g_acl_file,    sizeof(g_acl_file),     "%s/acl",            g_config_dir);

    /* create config directory */
    if (compat_mkdir(g_config_dir, 0755) < 0 && errno != EEXIST) {
        fprintf(stderr, "[%s] warning: mkdir %s: %s\n",
                g_agent_name, g_config_dir, strerror(errno));
    }

    /* touch passwd file so mosquitto_passwd -D won't fail on first run */
    if (!g_no_auth) {
        FILE *pf = fopen(g_passwd_file, "a");
        if (pf) {
            fclose(pf);
        }
    }

    /* signals */
#ifdef COMPAT_WINDOWS
    signal(SIGINT,  on_signal);
    signal(SIGTERM, on_signal);
#else
    struct sigaction sa;
    memset(&sa, 0, sizeof(sa));
    sa.sa_handler = on_signal;
    sigaction(SIGINT,  &sa, NULL);
    sigaction(SIGTERM, &sa, NULL);

    struct sigaction sa_ign;
    memset(&sa_ign, 0, sizeof(sa_ign));
    sa_ign.sa_handler = SIG_IGN;
    sigaction(SIGPIPE, &sa_ign, NULL);
#endif

    /* write config and start broker */
    if (write_mosquitto_conf() < 0) {
        return 1;
    }
    write_acl_file();

    if (broker_start() < 0) {
        return 1;
    }

    /* REST API server */
    compat_socket_t server_fd = make_server_socket(g_api_port);
    if (server_fd == COMPAT_INVALID_SOCKET) {
        fprintf(stderr, "[%s] failed to create REST API socket on port %d\n",
                g_agent_name, g_api_port);
        broker_stop();
        return 1;
    }

    /* startup banner */
    printf("[%s] Herald active — broker port=%d  api port=%d  auth=%s\n",
           g_agent_name, g_broker_port, g_api_port,
           g_no_auth ? "off" : "on");
    printf("[%s]   config dir: %s\n", g_agent_name, g_config_dir);
    printf("[%s]   mosquitto:  %s\n", g_agent_name, g_mosquitto_bin);
    printf("[%s]   REST: POST /credentials/issue | POST /credentials/revoke"
           " | GET /health\n", g_agent_name);

    /* main loop */
    time_t last_log = time(NULL);

    while (g_running) {
        fd_set rfds;
        FD_ZERO(&rfds);
        FD_SET(server_fd, &rfds);

        struct timeval tv;
        tv.tv_sec  = BROKER_CHECK_SEC;
        tv.tv_usec = 0;

        int sel = select(COMPAT_SELECT_NFDS(server_fd), &rfds, NULL, NULL, &tv);

        if (sel > 0 && FD_ISSET(server_fd, &rfds)) {
            http_serve_once(server_fd);
        }

        if (broker_check() == 1) {
            broker_start();
        }

        time_t now = time(NULL);
        if (now - last_log >= LOG_INTERVAL_SEC) {
            printf("[%s] status: broker_pid=%d restarts=%d creds=%d\n",
                   g_agent_name, (int)g_broker_pid,
                   g_broker_restarts, g_cred_count);
            last_log = now;
        }
    }

    printf("[%s] shutting down\n", g_agent_name);
    compat_close_socket(server_fd);
    broker_stop();
    compat_winsock_cleanup();
    return 0;
}
